package com.example.tuilivestream.utils
import android.content.Context

/**
 * Created by Anggit Prayogo on 19/10/23.
 */
abstract class TUILiveRoom {
    companion object {
        fun sharedInstance(context: Context): TUILiveRoom {
            return TUILiveRoomImpl.sharedInstance(context)
        }
    }

    /**
     * CreateRoom
     *
     * @param roomId generated by the server
     * @param name room's name
     * @param coverUrl room's cover
     */
    abstract fun createRoom(roomId: Int, name: String, coverUrl: String)

    /**
     * EnterRoom
     *
     * @param roomId generated by the server
     */
    abstract fun enterRoom(roomId: Int)

    /**
     * Set the event callbacks of the component
     *
     * @param listener listener
     */
    abstract fun setListener(listener: TUILiveRoomListener)
}
